version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - restore_cache:
          key: v1-lint-cache-{{ checksum ".eslintrc.js" }}
      - run: npx --no-install eslint . --cache
      - save_cache:
          key: v1-lint-cache-{{ checksum ".eslintrc.js" }}
          paths:
            - .eslintcache
      - run: npx --no-install jest --ci --runInBand --bail --silent --coverage --projects jest.config.js jest.config.jsdom.js
workflows:
  build-and-test:
    jobs:
      - build-and-test
##
