# version: 2.1
# jobs:
#   build-and-test:
#     docker:
#       - image: circleci/node:10.13.0
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-v1{{ checksum "package-lock.json" }}
#       - run: npm ci
#       - save_cache:
#           key: dependency-cache-v1{{ checksum "package-lock.json" }}
#           paths:
#             - ./node_modules
#       - run: npx --no-install eslint .
#       - run: npx --no-install jest --ci --runInBand --bail --silent --coverage --projects jest.config.js jest.config.jsdom.js
# workflows:
#   build-and-test:
#     jobs:
#       - build-and-test
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: ls .
      - persist_to_workspace:
          root: ./
          paths:
            - '*'
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: '[ ! -d node_modules ] && npm ci --loglevel warn --yes || echo package.json and package-lock.json unchanged. Using cache.'
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: echo buildzzzzzz
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - run: npx --no-install jest --ci --runInBand --bail --silent --coverage --projects jest.config.js jest.config.jsdom.js
      - run: ls ./
      - run: echo testzzzzzz
  lint:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - run: npx --no-install eslint .
      - run: ls ./
      - run: echo lintzzzz
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
#   build:
#     docker:
#       - image: circleci/node:10.13.0
#     steps:
#       - checkout
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#       - run: npm ci
#       - save_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#           paths:
#             - ./node_modules
#       - persist_to_workspace:
#           root: /
#           paths:
#             - '*'
#   test:
#     docker:
#       - image: circleci/node:10:13:0
#     steps:
#       - run: echo test steps
#       - attach_workspace:
#           at: /workspace
#       - run: ls /workspace

