version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install --no-save
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
#



dependency-cache-F2ddetoAGMvKv42xS0dOE8c5DjZ6v3Ci7w1XdEVJwFo=


dependency-cache-Ig0iTrH_jdPc6Az0kQ6hLyxDkRP7e9irtE863guUWAU=
